# Generated by Django 5.1.3 on 2024-12-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoiceoption",
            name="text",
            field=models.TextField(),
        ),
    ]
