# Generated by Django 5.1.3 on 2024-12-09 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="multiplechoiceanswer",
            name="answer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multiple_choice_answer",
                to="quiz.answer",
            ),
        ),
        migrations.AddField(
            model_name="multiplechoiceanswer",
            name="selected_option",
            field=models.ManyToManyField(
                blank=True, null=True, to="quiz.multiplechoiceoption"
            ),
        ),
        migrations.AddField(
            model_name="openendedanswer",
            name="answer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="open_ended_answer",
                to="quiz.answer",
            ),
        ),
        migrations.AddField(
            model_name="multiplechoiceoption",
            name="question",
            field=models.ForeignKey(
                limit_choices_to={"question_type": "multiple_choice"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multiple_choice_options",
                to="quiz.question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="quiz.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
            ),
        ),
        migrations.AddField(
            model_name="singlechoiceanswer",
            name="answer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="single_choice_answer",
                to="quiz.answer",
            ),
        ),
        migrations.AddField(
            model_name="singlechoiceoption",
            name="question",
            field=models.ForeignKey(
                limit_choices_to={"question_type": "single_choice"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="single_choice_options",
                to="quiz.question",
            ),
        ),
        migrations.AddField(
            model_name="singlechoiceanswer",
            name="selected_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.singlechoiceoption",
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question", "user"], name="quiz_answer_questio_48272c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("question", "user"), name="unique_user_answer"
            ),
        ),
    ]
