# Generated by Django 5.1.3 on 2024-12-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoiceanswer",
            name="selected_option",
            field=models.ManyToManyField(blank=True, to="quiz.multiplechoiceoption"),
        ),
    ]
