# Generated by Django 5.1.3 on 2024-12-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelanalysisresult",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_analysis",
                to="quiz.quiz",
            ),
        ),
    ]
